"""WORKSPACE collector — is the gate operating on an isolated, disposable run area?

Ported from v3.8 `workspace.py`. The invariant that file existed to defend is unchanged:

    the tree that gets mutated is never the tree the human is editing.

v3.8's `create` both BUILT the run area and printed a report. In v4.0 building the run area
is the orchestrator's job (the `ExecutionAdapter` is constructed around an existing run
area), so this collector OBSERVES the isolation that was established and states, in typed
evidence, exactly how strong it is. Everything v3.8 proved is still proved here:

  * git-worktree isolation is recognised by comparing the private git dir against the shared
    common dir, so a linked worktree is distinguished from a plain clone/copy;
  * the copy fallback is recognised (a `git init`-ed copy, so faultgen's clean-tree
    requirement still holds), and an un-git'd copy is reported as a warning rather than
    silently disabling the fault audit;
  * the DISPOSABILITY ASSERTION is preserved: a run area with no `.shipgate-run-area` marker,
    or one whose marker names a different source repo, is reported — the gate must never
    delete a directory it does not own, and it must never quietly adopt another run's area;
  * SCAFFOLDING HIDING is preserved verbatim in mechanism: a PER-WORKTREE excludes file
    (`extensions.worktreeConfig` + `core.excludesFile --worktree`), never `.git/info/exclude`,
    which from a linked worktree resolves to the SHARED file and would suppress the user's
    own untracked files in their own checkout.

Every git invocation goes through `ctx.adapter.run_internal(argv)` — a gate-authored argv
list, never a shell string, always with `cwd` inside the run area (`git -C` points it at the
source repo when that is what is being read).

FIX-WORKSPACE-NEVER-WRITES-USER-TREE: v3.8's `hide_scaffolding` was also called on the
user's checkout root. This collector only ever writes inside the run area (the excludes file
lives in the worktree's PRIVATE git dir). The one unavoidable shared-config write —
`extensions.worktreeConfig`, which git requires before `--worktree` config resolves at all —
is performed only if it is not already enabled and is REPORTED in `warnings` instead of
being silent.
"""
import json
from pathlib import Path

from ..models.evidence import EvidenceKind
from .base import Collector

MARKER = ".shipgate-run-area"
#: Kept byte-identical to v3.8: git is the single source of truth for "what is scaffolding".
#: node_modules is here because the bootstrap installs the gate's own tooling into the run
#: area, and repos WITHOUT a .gitignore — common for the AI-generated apps this gate targets —
#: would otherwise show `?? node_modules/` and the fault audit would refuse to run.
# FIX-WORKSPACE-HIDE-OWN-OUTPUT: the gate writes its own artifacts into the run area (the UI
# crawl's evidence directory, the mutation runner's scratch and report trees, lockfiles a tool
# regenerates). Those were NOT hidden, so a later collector — the fault audit, which requires a
# clean tree to prove a revert was complete — refused on dirt the gate itself had created. Every
# path the gate or its tools are known to write is scaffolding, not a repository change.
SCAFFOLD = [
    MARKER,
    "shipgate-workdir/",
    "node_modules/",
    ".venv/",
    "__pycache__/",
    # gate-authored evidence
    "shipgate-ui-evidence/",
    ".shipgate-heldout/",
    ".shipgate-fault",
    # mutation tooling scratch and reports
    ".stryker-tmp/",
    "reports/mutation/",
    "mutation-report.json",
    "mutation-report.xml",
    ".mutmut-cache",
    ".cosmic-ray/",
    "cosmic-ray.sqlite",
    # regenerated by an install the gate triggered
    "package-lock.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    # common tool caches
    ".pytest_cache/",
    ".playwright/",
    "playwright-report/",
    "test-results/",
    "coverage/",
]


def _git(ctx, argv, cwd, timeout=60):
    """Gate-owned git. Returns the ExecResult, or None when the adapter refused/it crashed."""
    try:
        return ctx.adapter.run_internal(["git", *argv], cwd=str(cwd), timeout=timeout)
    except Exception:  # noqa: BLE001 — a refused/failed probe is an unknown, never a success
        return None


def _out(res):
    return (res.stdout or "").strip() if (res is not None and res.returncode == 0) else ""


def _read_json(path):
    try:
        return json.loads(Path(path).read_text())
    except Exception:  # noqa: BLE001
        return None


def _read_marker(area):
    doc = _read_json(Path(area) / MARKER)
    return doc if isinstance(doc, dict) else None


def _abs_gitpath(area, text):
    if not text:
        return None
    p = Path(text)
    return p if p.is_absolute() else (Path(area) / p)


class WorkspaceCollector(Collector):
    """Observe the run area's isolation, disposability and scaffolding state.

    Options: `hide_scaffolding` (default True — write the per-worktree excludes file so the
    run area stays clean for the fault audit).
    """

    kind = EvidenceKind.WORKSPACE
    name = "workspace"
    version = "4.2.2"

    def collect(self, ctx):
        area = Path(ctx.run_area).resolve() if ctx.run_area else None
        if area is None or not area.is_dir():
            return self.error(ctx, f"run area is not a directory: {ctx.run_area!r}")
        repo = Path(ctx.repo).resolve() if ctx.repo else None

        warnings = []
        marker = _read_marker(area)
        if marker is None:
            wd = Path(ctx.workdir) if ctx.workdir else area / "shipgate-workdir"
            prov = _read_json(wd / "workspace.json")
            marker = prov if isinstance(prov, dict) else None

        # --- kind ---------------------------------------------------------------------------
        kind, is_git = self._classify(ctx, area, repo, marker, warnings)

        # --- disposability assertion (v3.8 assert_disposable, as an observation) -------------
        if marker is None:
            warnings.append(
                f"no {MARKER} marker in {area}: this directory cannot be asserted disposable, "
                f"so the gate must never delete it")
        else:
            src = marker.get("source")
            if src and repo and Path(src) != repo:
                warnings.append(
                    f"run-area marker names source {src!r}, but this run's repository is "
                    f"{str(repo)!r} — a concurrent run may be using this area")

        if repo is not None and area != repo:
            try:
                area.relative_to(repo)
                warnings.append(
                    f"the run area {area} lives INSIDE the repository under test; editors, "
                    f"bundlers and the gate's own recon will enumerate it as product code")
            except ValueError:
                pass

        isolated = bool(kind in ("worktree", "copy") and repo is not None and area != repo)
        if kind == "in-place":
            warnings.append(
                "IN-PLACE: fault injection writes to the user's working tree. A crash between "
                "inject and revert leaves their files broken, and the fault audit's clean-tree "
                "requirement is forfeit unless the tree is already clean")
        if repo is None:
            warnings.append("no source repository was supplied; isolation cannot be asserted")

        # --- snapshot commit -----------------------------------------------------------------
        snapshot = marker.get("snapshot_commit") if marker else None
        if not snapshot and is_git:
            snapshot = _out(_git(ctx, ["rev-parse", "HEAD"], area)) or None
        if snapshot is not None:
            snapshot = str(snapshot)
        if is_git and not snapshot:
            warnings.append("the run area has no resolvable HEAD, so what was gated cannot be named")

        # --- scaffolding hiding ----------------------------------------------------------------
        hidden = []
        if is_git and ctx.option("hide_scaffolding", True):
            hidden = self._hide_scaffolding(ctx, area, kind, warnings)
        elif not is_git:
            warnings.append(
                "the run area is not a git repository: scaffolding cannot be hidden through git "
                "and the fault audit's clean-tree guard cannot be satisfied (v3.8 `git init`-ed "
                "the copy for exactly this reason)")

        # --- clean-for-faultgen ------------------------------------------------------------------
        if is_git:
            res = _git(ctx, ["status", "--porcelain"], area)
            if res is None or res.returncode != 0:
                warnings.append("could not read `git status` in the run area; cleanliness is unknown")
            else:
                left = [l for l in (res.stdout or "").splitlines() if l.strip()]
                if left:
                    warnings.append(
                        f"run area is NOT clean for the fault audit ({len(left)} entry/entries): "
                        + "; ".join(left[:8]))

        payload = {
            "kind": kind,
            "isolated": isolated,
            "runArea": str(area),
            "sourceRepo": str(repo) if repo is not None else "",
            "snapshotCommit": snapshot,
            "scaffoldingHidden": hidden,
            "warnings": warnings,
        }
        uncovered = [] if isolated else ["isolation: the gate is not operating on an isolated copy"]
        return self.collected(
            ctx, payload,
            note=f"{kind} run area; isolated={isolated}; {len(warnings)} warning(s)",
            uncovered=uncovered)

    # --- internals ---------------------------------------------------------------------------
    def _classify(self, ctx, area, repo, marker, warnings):
        """(kind, is_git). The marker is believed only when the filesystem agrees with it."""
        inside = _out(_git(ctx, ["rev-parse", "--is-inside-work-tree"], area)) == "true"
        derived = None
        if repo is not None and area == repo:
            derived = "in-place"
        elif inside:
            private = _abs_gitpath(area, _out(_git(ctx, ["rev-parse", "--absolute-git-dir"], area)))
            common = _abs_gitpath(area, _out(_git(ctx, ["rev-parse", "--git-common-dir"], area)))
            try:
                linked = bool(private and common and private.resolve() != common.resolve())
            except OSError:
                linked = False
            derived = "worktree" if linked else "copy"
        else:
            derived = "copy"

        declared = (marker or {}).get("mode")
        if declared in ("worktree", "copy", "in-place") and declared != derived:
            # A marker that disagrees with the tree is not authoritative — the tree is.
            warnings.append(
                f"run-area marker declares mode {declared!r} but the filesystem says {derived!r}; "
                f"the observed value is reported")
        return derived, inside

    def _hide_scaffolding(self, ctx, area, kind, warnings):
        """v3.8 `hide_scaffolding`, restricted to the run area.

        A linked worktree gets a PER-WORKTREE excludes file. `.git/info/exclude` is shared
        across worktrees — a pattern written there from a linked worktree also suppresses
        untracked files in the user's main checkout — so it is used only for a standalone
        copy, whose `.git` belongs to nobody but the run area.
        """
        body = "\n".join(SCAFFOLD) + "\n"
        if kind == "worktree":
            private = _abs_gitpath(area, _out(_git(ctx, ["rev-parse", "--absolute-git-dir"], area)))
            if private is None:
                warnings.append("could not resolve the worktree's private git dir; scaffolding not hidden")
                return []
            ex = private / "shipgate-exclude"
            try:
                ex.parent.mkdir(parents=True, exist_ok=True)
                ex.write_text(body)
            except OSError as exc:
                warnings.append(f"could not write {ex}: {exc}; scaffolding not hidden")
                return []
            enabled = _out(_git(ctx, ["config", "--get", "extensions.worktreeConfig"], area))
            if enabled.lower() != "true":
                res = _git(ctx, ["config", "extensions.worktreeConfig", "true"], area)
                if res is None or res.returncode != 0:
                    warnings.append(
                        "extensions.worktreeConfig could not be enabled, so per-worktree excludes "
                        "do not resolve; scaffolding is not hidden")
                    return []
                warnings.append(
                    "enabled extensions.worktreeConfig in the SHARED git config (git requires it "
                    "before --worktree config resolves); no file in your checkout was touched")
            res = _git(ctx, ["config", "--worktree", "core.excludesFile", str(ex)], area)
            if res is None or res.returncode != 0:
                warnings.append("could not set the per-worktree core.excludesFile; scaffolding not hidden")
                return []
            return list(SCAFFOLD)

        info = area / ".git" / "info"
        try:
            info.mkdir(parents=True, exist_ok=True)
            (info / "exclude").write_text(body)
        except OSError as exc:
            warnings.append(f"could not write {info / 'exclude'}: {exc}; scaffolding not hidden")
            return []
        return list(SCAFFOLD)
