"""Content hashing and reproducible tree digests. Stdlib only."""
import hashlib
import os
from pathlib import Path

_CHUNK = 1 << 20

# Directories and files that are never part of a runtime tree digest: test scaffolding,
# packaging metadata, generated state, and — critically — the artifacts the GATE ITSELF writes
# into the run area while it works.
#
# FIX-TREE-DIGEST-SELF-DISTURBANCE: this list and `collectors.workspace.SCAFFOLD` are the same
# idea expressed twice, and they had drifted. The workspace collector was taught to hide the
# gate's own outputs (the UI crawl's evidence directory, mutation reports, regenerated
# lockfiles) so the fault audit would stop refusing on dirt the gate created — but the tree
# DIGEST was never told. The consequences were worse than the original bug:
#
#   * `subject.treeDigest` changed DURING a run, so the identity of the thing being evaluated
#     was not stable across the evaluation of it;
#   * two runs over an unmodified repository produced different digests, which quietly breaks
#     reproducibility — the property the canonical decision exists to provide;
#   * every digest-keyed cache lookup missed, because the key could never repeat.
#
# `tests/unit/test_hashing.py` now asserts the two sets agree, so they cannot drift again.
DEFAULT_TREE_EXCLUDES = (
    # version control, language and tool caches
    ".git", "__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache",
    "node_modules", ".venv", "venv", ".tox",
    # the gate's own state and test scaffolding
    "shipgate-workdir", "tests", "selftest", "validation",
    ".shipgate-run-area", ".shipgate-heldout", ".shipgate-fault",
    "shipgate-ui-evidence",
    # mutation tooling scratch and reports
    ".stryker-tmp", "reports/mutation", "mutation-report.json", "mutation-report.xml",
    ".mutmut-cache", ".cosmic-ray", "cosmic-ray.sqlite",
    # regenerated by an install the gate triggered
    "package-lock.json", "pnpm-lock.yaml", "yarn.lock",
    # browser and coverage output
    ".playwright", "playwright-report", "test-results", "coverage",
)


def sha256_bytes(data):
    return hashlib.sha256(data).hexdigest()


def sha256_text(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        while True:
            b = fh.read(_CHUNK)
            if not b:
                break
            h.update(b)
    return h.hexdigest()


def _split_excludes(excludes):
    """Bare names match ANY path segment; entries containing '/' match a path PREFIX.

    The distinction matters. `reports/mutation` is the mutation runner's output directory, but
    a repository may legitimately have its own top-level `reports/` full of real source — and
    excluding that from the subject digest would hide part of the thing being evaluated, which
    is a worse failure than the one the exclusion exists to fix. Precision over convenience.
    """
    names, prefixes = set(), []
    for e in excludes:
        e = e.strip("/")
        if not e:
            continue
        if "/" in e:
            prefixes.append(e)
        else:
            names.add(e)
    return names, tuple(prefixes)


def tree_files(root, excludes=DEFAULT_TREE_EXCLUDES):
    """Deterministically ordered (relpath, abspath) pairs for a directory tree.

    Symlinks are NOT followed (a symlink out of the tree would let content outside the
    digest scope influence a "whole tree" hash); they are recorded by their target text.
    """
    root = Path(root).resolve()
    names, prefixes = _split_excludes(excludes)

    def excluded(rel):
        if any(seg in names for seg in rel.split("/")):
            return True
        return any(rel == p or rel.startswith(p + "/") for p in prefixes)

    out = []
    for dirpath, dirnames, filenames in os.walk(root, followlinks=False):
        base = Path(dirpath).relative_to(root).as_posix()
        base = "" if base == "." else base
        dirnames[:] = sorted(
            d for d in dirnames if not excluded(f"{base}/{d}" if base else d))
        for name in sorted(filenames):
            p = Path(dirpath) / name
            rel = p.relative_to(root).as_posix()
            if excluded(rel):
                continue
            out.append((rel, p))
    out.sort(key=lambda t: t[0].encode("utf-8"))
    return out


def tree_digest(root, excludes=DEFAULT_TREE_EXCLUDES):
    """sha256 over 'mode\\tsha256\\trelpath\\n' lines — content AND executable bit AND path.

    The executable bit is in scope because a runtime tree whose script became non-executable
    (or whose data file became executable) is a materially different tree.
    """
    h = hashlib.sha256()
    for rel, p in tree_files(root, excludes):
        if p.is_symlink():
            line = f"link\t{sha256_text(os.readlink(p))}\t{rel}\n"
        else:
            mode = "755" if os.access(p, os.X_OK) else "644"
            line = f"{mode}\t{sha256_file(p)}\t{rel}\n"
        h.update(line.encode("utf-8"))
    return h.hexdigest()


def tree_manifest(root, excludes=DEFAULT_TREE_EXCLUDES):
    """The per-file listing behind `tree_digest`, for diffing a mismatch into a real cause."""
    entries = []
    for rel, p in tree_files(root, excludes):
        if p.is_symlink():
            entries.append({"path": rel, "mode": "link", "sha256": sha256_text(os.readlink(p))})
        else:
            entries.append({
                "path": rel,
                "mode": "755" if os.access(p, os.X_OK) else "644",
                "sha256": sha256_file(p),
            })
    return entries
